FROM arm64v8/python:3.9.16-slim-buster
COPY requirements.txt /opt/
ENV PATH "$PATH:/root/.cargo/bin"
RUN  set -ex \
    \
    && apt-get update && apt-get install -y --no-install-recommends gcc libc-dev curl wget xz-utils vim \
        && curl https://sh.rustup.rs -sSf > cargo.sh && /bin/bash ./cargo.sh -y \
    && rustup toolchain install nightly && rustup default nightly \
        && pip install --upgrade pip && pip install --disable-pip-version-check --no-cache-dir -r /opt/requirements.txt \
    && rm -rf /var/lib/apt/lists/*
COPY . /opt/fb_recover_keys
WORKDIR /opt/fb_recover_keys